### ISSUE TITLE
Mention this repo or the organization somewhere

### ISSUE THREAD

**Issue by NetSysFire** [Libera-Chat/libera-chat.github.io#1]
It took me a while to find this repo. It would be great if a link to this repo or the organization could be added somewhere, maybe near the footer where facebook and twitter are already mentioned.

**Comment by richrd** [comment]
A GitHub link was added there in this commit: https://github.com/Libera-Chat/libera-chat.github.io/commit/42619656453eb4196c994f2525f8d89d1977d6db
I suppose this can be closed.
