### ISSUE TITLE
Page title/header squashed over content for narrow window

### ISSUE THREAD

**Issue by adigitoleo** [Libera-Chat/libera-chat.github.io#109]
I don't know what it's called but the "Libera.Chat" header text (top left) gets squashed and drawn vertically over the content when the window is resized to a smaller horizontal width (~900 px). Screenshot attached. Just thought I'd let you know.

Cheers

![image](https://user-images.githubusercontent.com/34595875/124061760-d20b1280-da72-11eb-96a3-881a5cd34ff8.png)

**Comment by arunabhp75** [comment]
@adigitoleo, looks like browser specific issue,  which one are you using ?

**Comment by adigitoleo** [comment]
I'm using qutebrowser which is built on QtWebEngine, however after upgrading to QtWebEngine 5.15.5 the issue is gone (unless the screen is _really_ narrow, like 200px or something). I'll close it, thanks for pinging, I kinda forgot about this :)
