### ISSUE TITLE
Please clarify the existence of the Matrix protocol bridge and its Terms of Use

### ISSUE THREAD

**Issue by Mikaela** [Libera-Chat/libera-chat.github.io#113]
The website says nothing about the existence of Matrix protocol bridge, while it's difficult to use Libera.Chat without encountering it, and there is a common misconception around the Matrix protocol bridge that it is run by Libera.Chat Staff while looking into it deeply shows that it's ran by Element Matrix Services.

* [ ] Is it allowed to use it to bridge other IRC networks or entirely different protocols? #91 
  * [ ] I have heard staff saying that the bridge is only meant for Matrix users, but regardless I am aware of at least two projects bridging Telegram users to Libera.Chat through it?
* [ ] Sometimes people are kicked on Matrix side by the bridge due to inactivity. Is this something that is supposed to happen or part of the contact between Libera.Chat and Matrix.org? 
  * [ ] Why are some users immune to this? E.g. there are several users with realname `@telegram_<numeric-string>:feneas.org` that haven't existed since around 2020-10-24.
* [ ] How much power does Libera.Chat have in the administration of the bridge/homeserver? My understanding is that it's a paid service, are Libera.Chat paying to have it or is there some sort of sponsorship agreement?

These are just my open questions or questions brought to my attention and I would like them to be answered on Libera.Chat or other documentation instead of quoting other people from possibly incorrect memory.

**Comment by Mikaela** [comment]
I updated the issue/title as it was misunderstood to mean Matrix.org project or the EMS, while I meant the protocol. Additionally I added the last question I forgot during typing it.

**Comment by emersonveenstra** [comment]
This isn't a full answer, but it's at least something to link to:

- As of now double bridging is not allowed. However, as you note, this hasn't been enforced 100% of the time, so we're talking internally about if we want to allow it going forward.
- Libera requested idle kicks to prevent thousands of inactive/deactivated matrix users sitting in IRC channels until the end of time. I'm not sure why your TG bridge users aren't being kicked, but they should be.
- EMS runs the Libera.Chat homeserver and bridge, they've very kindly donated it to us.

**Comment by Mikaela** [comment]
Is `/mode +b *!*@2001:470:69fc:105::/64` the official method of opting out of bridging? https://github.com/matrix-org/matrix-appservice-irc/issues/1436 would be my Matrix side issue.

**Comment by emersonveenstra** [comment]
In the future, the solanum extban will be the correct way to do it.

Right now there's not a completely effective way to opt out of bridging. `/mode +b *!*@2001:470:69fc:105::/64` will mostly work, but Solanum can't see through cloaks to check IP bans. `/mode +b $r:@*:*` is another option but might get some false positives. 

We've added the FAQ that addresses your initial questions: https://libera.chat/guides/faq#can-i-connect-with-matrix so I'm going to close this out.

**Comment by Mikaela** [comment]
> Libera requested idle kicks to prevent thousands of inactive/deactivated matrix users sitting in IRC channels until the end of time. I'm not sure why your TG bridge users aren't being kicked, but they should be.

This issue has moved to https://github.com/matrix-org/matrix-appservice-irc/issues/1460 as the Telegram users still didn't get removed with the most recent kicking.

**Comment by heyakyra** [comment]
From my matrix.org account I was kicked from Libera.chat inactivity, but I'm unable to (re-)join any libera.chat rooms because of "No known servers" …any ideas?

**Comment by progval** [comment]
@heyakyra This is a Matrix-specific issue, please report it to matrix.org
