### ISSUE TITLE
Listed Clients

### ISSUE THREAD

**Issue by grimmy** [Libera-Chat/libera-chat.github.io#132]
While helping a user in #pidgin today setup SASL, I was looking for the [guide](https://libera.chat/guides/clients) when I stumbled across the [clients page](https://libera.chat/guides/clients). I was disappointed to see that [Pidgin](https://pidgin.im) was not listed there. Pidgin has a long and rich history which includes using Libera.chat and it's previous network as it's primary support channel since at least 2003 which is when I got involved in the project.

I brought this up in #libera and was told to create an issue here and to come up with a way to add a list of additional clients. I think an additional list is great as it could give exposure to many clients, but I think Pidgin deserves to be on the first page. I'm of course biased, but the [Google Trends results](https://trends.google.com/trends/explore?q=%2Fm%2F01hv6k,%2Fm%2F03szy,%2Fm%2F03szg,%2Fm%2F03t0h,%2Fm%2F0cw53x) seem to agree with me.

I was unable to add Konversations or Limechat as Google Trends some how breaks when they're added, but as you can see pidgin is searched for more than everything except mIRC. Also note that due to name collisions, we have to explicitly ask Google Trends for `Pidgin Software` where all the others are `Topic` searches.

At any rate, this issue is to hopefully open some discussion here but at the end of the day it's your website and you can recommend who you like and we'll just have to deal with that.

**Comment by emersonveenstra** [comment]
Sorry about that, definitely not intentional! The clients on there now are just the ones that I thought of when writing it.

The clients page is meant for first-time Libera users, so an exhaustive list of clients will end up overwhelming them and i'd rather not do that. However, I wouldn't mind Pidgin being added to the list.

**Comment by grimmy** [comment]
No worries, I didn't take it personally, just shows that we have more work to do to get back into peoples thoughts ;)

At any rate, should I create a pull request or is that something you all would rather handle?

**Comment by emersonveenstra** [comment]
feel free to make a PR :+1:
