### ISSUE TITLE
Please document your governance

### ISSUE THREAD

**Issue by Minoru** [Libera-Chat/libera-chat.github.io#18]
I'm currently looking to move my community off Freenode. The primary contenders are OFTC and Libera.chat. OFTC's strongest point, in my opinion, is their [Constitution document](https://oftc.net/constitution/): it explains exactly who can do what, and who has what responsibilities. They also have a [Staff page](https://oftc.net/staff/) which is like Freenode's "People" page. Together, these documents inspire much confidence in the future of OFTC.

[Libera.chat's inaugural post](https://oftc.net/staff/) already mentions that Libera.chat is a Swedish non-profit where all staff holds equal stakes, but I don't think this is enough. Ideally, I'd like a document explaining:

- **who exactly are current staff?** OFTC goes as far as listing real names here, but I'd personally be okay with nicknames;
- **do staff have different roles? If so, which roles each staff member currently holds?**;
- **how do people assume and leave roles?**;
- **how do you make decisions regarding the network?**;
- **who sponsors each machine that hosts the network, and on what terms?**.

I understand that Libera.chat is very young and might not have a policies for everything yet. I'd personally be satisfied with a barebones answers to the above: just a list of nicknames, "everyone is netops with root access to all machines", "changes to this policy are approved by majority vote, and ties can't happen because there's 13 of us". But please, please write this up.

**Comment by vilhalmer** [comment]
It would be great to have an Impressum page for the nonprofit as well. (I understand this may still be going through any number of levels of bureaucracy and I'm not actually sure what the requirements in Sweeden are.)

**Comment by petermolnar** [comment]
> who exactly are current staff? OFTC goes as far as listing real names here, but I'd personally be okay with nicknames;

In many countries, non-profits have legal obligations to certain levels of openness, like disclosing members, trustees, official address etc. Beyond this, Germany, for example, [by law requires an impressum page](https://www.ionos.com/digitalguide/websites/digital-law/a-case-for-thinking-global-germanys-impressum-laws/) for websites, so some level of information may not even be optional, but mandatory.

**Comment by swantzter** [comment]
All of these details are written down but not currently published on our website, partly because we were waiting for (optional) bureaucracy (which we're still waiting for) and partly because we have been awaiting our next meeting to ratify some editorial changes and approval/discussion of what exactly to publish.

An Impressum is not required by Swedish law, but some contact details make sense to publish.

I hope we can get this sorted out before the end of the week

**Comment by kurahaupo** [comment]
Can we get a link to Libera's entry in the Swedish government's register of non-profit entities?

I assume they make such a register visible on the web?

At minimum please can we have the registration number?

**Comment by swantzter** [comment]
@kurahaupo that's still being processed by the Swedish tax authority. You'll be able to find the organisation via services like https://allabolag.se once that's done.

Legally, the type of organisation Libera Chat is ("ideell förening") doesn't _require_ registration to be considered a legal entity, just bylaws and a constituting meeting. We have however sent in the form to get an organisation number since it makes a lot of dealings easier, such as with the government, tax authority and banks.

**Comment by real-or-random** [comment]
>     * **who exactly are current staff?** OFTC goes as far as listing real names here, but I'd personally be okay with nicknames;

Pages like `/chanreg` tell me to contact staff members on IRC, e.g.: "please feel free to drop any of the team members a line on IRC." But this is not exactly actionable without listing the staff members. 

For now, it will already be helpful to document how to reach out i.e., 1) *in which channel* should I look for them and maybe 2) how to identify them within IRC (ops?).

**Comment by swantzter** [comment]
We just pushed out https://libera.chat/about and some updates to the bylaws (4ec73fdf8173b3ccc0f33480f2d64610fe25a7ea, and 9bb517eab9064b640a5d4daaa33ab46e3ba64cd3) I hope this clarifies most points?

As for sponsors, we will list them (in fact providing some PR in return is a requirement in the Swedish tax code to be able to call something a sponsorship) on the website and in the server MOTD's, but we'll have to deal with that once things have calmed down a little and we have the bandwidth to do it that'll likely include information on how to sponsor and what that means. Currently a handful of servers are provided by organisation members directly, and the rest are provided on terms along the lines of "you provide us a server that we will fully manage and administer, in return we will put your organisation's name on the website and in the MOTD" Publishing sponsors is tracked in #40

Is there anything that feels left open on this issue or does this make it closeable for now?

**Comment by Minoru** [comment]
Yes, I think all the points are addressed, so I'll close this. Thanks for your work!

**Comment by kurahaupo** [comment]
@real-or-random Does [my PR](https://github.com/kurahaupo/libera-chat.github.io/commit/d40532763413908f0ca90662010b1b90f039ad72) do what you want?

**Comment by kurahaupo** [comment]
@Minoru what about [the item raised by @real-or-random](#issuecomment-846544089) - to better explain "how to contact staff"?

**Comment by Minoru** [comment]
@kurahaupo I expect it'll be addressed by your PR. So, basically, the two commits referenced above answer most of the questions, sponsors will be addressed in #40, and the question will be addressed by your PR. So, nothing left to do in this issue. (But the owners of the repo can reopen this of course, it's up to them how to structure their workflow.)

**Comment by real-or-random** [comment]
> @real-or-random Does [my PR](https://github.com/kurahaupo/libera-chat.github.io/commit/d40532763413908f0ca90662010b1b90f039ad72) do what you want?

Yes, thanks! :+1:
