### ISSUE TITLE
Please provide a webchat

### ISSUE THREAD

**Issue by Minoru** [Libera-Chat/libera-chat.github.io#19]
IRC is not exactly the trendiest technology these days, and some people might not have an IRC client yet. For such cases, it'd be nice to have a webpage similar to webchat.freenode.net, so those people can still join.

(My use-case for this is a channel for a FOSS project where a user might pop up to ask a quick question.)

**Comment by legoktm** [comment]
You can use https://kiwiirc.com/nextclient/irc.libera.chat/?#<channel> for webchat, however it would be nice if Libera Chat hosted their own.

**Comment by zanhecht** [comment]
> You can use https://kiwiirc.com/nextclient/irc.libera.chat/?#channel for webchat, however it would be nice if Libera Chat hosted their own.

Is it a problem that kiwiirc is [sponsored](https://kiwiirc.com/blog/Kiwi_IRC_gets_sponsored_by_PrivateInternetAccess) by Andrew Lee's PrivateInternetAccess? Is it sufficiently independent of Lee, or are there concerns about what happened to freenode happening to it?

**Comment by Freso** [comment]
> Is it a problem that kiwiirc is [sponsored](https://kiwiirc.com/blog/Kiwi_IRC_gets_sponsored_by_PrivateInternetAccess) by Andrew Lee's PrivateInternetAccess? Is it sufficiently independent of Lee, or are there concerns about what happened to freenode happening to it?

PIA is entirely separate from Lee: https://twitter.com/shadowcat_mst/status/1395043349342703619

**Comment by emersonveenstra** [comment]
we now have a webchat at https://web.libera.chat/
