### ISSUE TITLE
Recommend against using `pidgin`

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [Libera-Chat/libera-chat.github.io#192]
The client contains a bad IRC frontend that contains no server window, and uses modals to display wallops and some CTCP requests.

**Comment by glguy** [comment]
Same as on https://github.com/Libera-Chat/libera-chat.github.io/issues/202#issuecomment-1028423462 I would like us not to get in the business of making strong recommendations for or against client software.

**Comment by A-UNDERSCORE-D** [comment]
Sounds good!
