### ISSUE TITLE
Please provide a Matrix bridge with matrix.org

### ISSUE THREAD

**Issue by Minoru** [Libera-Chat/libera-chat.github.io#20]
Matrix.org has a bridge to Freenode, and some people used this in my channel. I'd prefer to keep those people if I migrate the channel to Libera.chat, so it'd be nice if there was a bridge from Matrix to libera.chat.

**Comment by Minoru** [comment]
To be clear, by "a bridge" I mean the ability for a Matrix user to join #_liberachat#somachannel:matrix.org and talk to people on #somechannel on Libera.chat. Full room bridging, where a special service creates puppet account, is not appealing to me at the moment and IMHO can be omitted.

**Comment by Seirdy** [comment]
It might be desirable to use a homeserver besides the `matrix.org` one since that one tends to get overloaded and its dominance isn't great for decentralization. More discussion is happening in `#matrix` on libera.chat.

**Comment by Minoru** [comment]
The corresponding matrix.org issue is https://github.com/matrix-org/matrix-appservice-irc/issues/1324.

**Comment by hramrach** [comment]
actually, the Matrix federation support makes it possible to have completely seamless bridge - that is all channels on irc appear as rooms on libera.chat home server, all irc users appear as users on libera.chat home server. Not sure if that's what 'puppet account service' means. Also not sure such bridge actually exists - all I have seen are really clunky incomprehensible hacks.

**Comment by Minoru** [comment]
@hramrach I updated my comment to use the canonical term, [plumbed rooms](https://matrix.org/docs/guides/types-of-bridging#plumbed-rooms). This exists on matrix.org for Freenode, OFTC and some others, but [has some limitations](https://github.com/newsboat/newsboat/issues/1643#issuecomment-845107556) which make the IRC side feel second-claass to me — that's why my comment says that room plumbing is not appealing to me at the moment.

**Comment by hramrach** [comment]
yes, it's the plumbed rooms that are responsible for most of the confusion. Some rooms at random are plumbed, others are not. That makes different rooms behave differently for no apparent reason.

**Comment by Minoru** [comment]
Quoting from #libera-matrix:

17:55:41 < halfy_> hi folks
17:55:49 < halfy_> or rather, let me use my bridge
17:56:07 < halfy> HI! right, bridge is nearly here now. We're just going through the testing phase.
17:56:18 < sm> fantastic, go halfy_ go
17:56:21 < technomancy> huzzah
17:56:30 < emorrp1_IRC> hello halfy_ from IRC side, thanks for all your hard work
17:57:29  * ilmari bounces excitedly
17:57:59 < halfy> we're also moving away from `#libera_` style alises which i'm sure will excite a few of you :)

The time is UTC, i.e. this was said 10 minutes ago.

**Comment by ShadowJonathan** [comment]
That's half the story, the whole story is that they're going to use `libera.chat` as a matrix server, and that the mapping is going to become `#channel:libera.chat` (if i'm not mistaken)

**Comment by SISheogorath** [comment]
Plumped rooms are important to prevent an "IRC-first" requirement. We have projects with existing matrix communities and want to bring the IRC side back that got lost by dropping freenode, then this won't be possible with libera, if no plumped rooms are possible.

This makes libera an undesirable IRC network for these communities.

**Comment by emersonveenstra** [comment]
The matrix bridge is up and running now, plumbing works the same way as it does on freenode. Thanks for your patience while we got everything sorted!

**Comment by kevincox** [comment]
There appears to be an issue with the SASL auth. Whereas for freenode you could use user:pass this appears to cause a failure now.

```
Reconnecting to network...
Your connection to the IRC network 'irc.libera.chat' has been lost. 
Connecting to the IRC network 'irc.libera.chat' as kevincox...
There was an error authenticating you over SASL. You may need to update your details and !reconnect. The error was: err_saslfail SASL authentication failed
You've been connected to the IRC network 'irc.libera.chat' as kevincox. User modes +R have been set.
```

Should this be a separate issue?

**Comment by kevincox** [comment]
Oops, my mistake. It just works differently than freenode. You need to use `!username` now to set the username. After doing that it seems to work. 🎉
