### ISSUE TITLE
Recommend against using ```Polari```.

### ISSUE THREAD

**Issue by RealKindOne** [Libera-Chat/libera-chat.github.io#202]
https://wiki.gnome.org/Apps/Polari

Why? The client tries to do things "different" and this creates confusion for both new and long time IRC users.

These are just some of the issues during my limited testing: 

Cannot see mode changes in channel while you are in the channel. This includes bans/quiets/op/voice/whatever.

Does not show any numerics or messages. This includes 'user is +R', 'user is +g', you are banned/quieted/invite only channel, registered users only, and everything else. This makes it very difficult to figure out things.

Unidentified user tries to join a cmode +r channel, the channel window is created but the user is not actually in the channel. User will think they are actually in the channel.

Client "eats" the first ```#``` from channel names in the channel sidebar if the channel has two or more.

Cannot see ```/msg @#channel test``` while op.

```/mode``` is a ```unknown command```

```/quote```  is an ```unknown command```, so you are effectively limited to using whatever is built into the IRC client.

```/whois``` output is extremely lacking. ```/whois memoserv``` only shows ```User: Memo Services - Last activity: Unavailable```

I used version 3.38 from https://packages.debian.org/bullseye/polari for this.

**Comment by glguy** [comment]
I think you're right that people should perhaps avoid this client, but we don't currently make any client recommendations beyond an intentionally limited list to get new people started. There wouldn't be a good place to put this kind of information, and I wouldn't want us to get in the business of expressing various strong opinions on various software.
