### ISSUE TITLE
Bylaws clarifications

### ISSUE THREAD

**Issue by ProgVal** [Libera-Chat/libera-chat.github.io#28]
Hi,

First, thanks a lot for https://libera.chat/bylaws

I am told you have a general meeting tomorrow to clarify/improve them, so here is a list of suggestions that you may or may not want to take into account:

1. Who are "members"? Is it a formal name for staffers, or does it include regular users/stakeholders?
2. What are the criteria for membership? (doesn't have to be in the bylaws, but it would be nice to have some informal explanation)
3. Make the following public, unredacted: annual reports, financial statements (even if it's just 0€ everywhere), and audit reports
4. Consider extending "Monthly General Meeting" paragraph 9 to making the documents public to everyone (with sensitive info redacted, of course)

Thanks!

**Comment by edk0** [comment]
jfyi for the member thing: the intent is that all staff are invited, and encouraged but not required, to become members of the nonprofit. The idea is that we primarily operate on the basis of staff consensus, rather than explicit voting; the voting members are there to ensure that formal decisions reflect that consensus and that there's no individual or small group of leaders that can subvert things.

**Comment by nemobis** [comment]
If the members are supposed to be people who volunteer to the operation of the association's services, that's something worth mentioning explicitly.

**Comment by swantzter** [comment]
I believe https://libera.chat/about now clarifies point 1 and 4.

The criteria for membership right now is "becoming staff" but I believe we'll want to consider refining it later, in fact there are already proposals being drafted for consideration.

I've tracked point 2 and 4 for internal discussion on upcoming Monthly General Meetings, does that qualify as handled/answered making this issue closeable? I don't see any more immediately actionable items

**Comment by ProgVal** [comment]
Thanks.

> I believe https://libera.chat/about now clarifies point 1 and 4.

Do you mean 1 and 3?

> I've tracked point 2 and 4 for internal discussion on upcoming Monthly General Meetings, does that qualify as handled/answered making this issue closeable? I don't see any more immediately actionable items

Let's keep it open until the changes are "released", even if there's nothing to be done right now? But feel free to close it if you want to.

Thanks again.

**Comment by emersonveenstra** [comment]
1 and 2 are answered in: https://libera.chat/bylaws#membership

3 and 4 are answered in: https://libera.chat/bylaws#monthly-general-meeting (item 10)

**Comment by ProgVal** [comment]
Excellent, thanks!
