### ISSUE TITLE
Add Adiirc chat client to clients.md

### ISSUE THREAD

**Issue by ashburry-chat-irc** [Libera-Chat/libera-chat.github.io#305]
Adiirc is FREE and works on Windows, and with Linux using Wine. It has full (or near full) support of mIRC Scripting Language. Website at **https://www.adiirc.com/**

**Comment by glguy** [comment]
Adiirc is mentioned elsewhere on the website. Many clients are missing from clients.md as it isn't meant to be a comprehensive list.
