### ISSUE TITLE
How can I register?

### ISSUE THREAD

**Issue by heipiao233** [Libera-Chat/libera-chat.github.io#309]
My IP is asked for use SASL, using SASL needs to verify my email address, that needs to connect with irc.libera.chat, connecting needs to use SASL. So how can I register?

**Comment by phy1729** [comment]
The suggested workaround is in the [SASL guide](https://libera.chat/guides/sasl).

> If your home internet providers are restricted, consider using public access wifi hotspots such as those provided by most libraries and many school or work campuses. If you are concerned about access point privacy, you can [change your password](https://libera.chat/guides/sendpass) once you are on a network you trust.

Should probably be crosslinked from the registration guide so it's more discoverable in cases like this.

**Comment by heipiao233** [comment]
I am using a desktop computer and cannot connect to any WiFi other than home WiFi or mobile hotspot (via mobile network). I have tried using a proxy, but they all require SASL. My ISP is China Telecom.

**Comment by aaronmdjones** [comment]
Please e-mail support@libera.chat and we can probably work something out.
