### ISSUE TITLE
Clarify “Libera Chat” vs. “Libera.Chat”

### ISSUE THREAD

**Issue by AndrewKvalheim** [Libera-Chat/libera-chat.github.io#31]
Is the name spelled “Libera Chat” or “Libera.Chat”? Currently both are used inconsistently throughout the website and I don’t know how to refer to the project.

**Comment by swantzter** [comment]
Libera Chat is the legal name of the organisation, Libera.Chat is the network

**Comment by AndrewKvalheim** [comment]
Thanks. I see now that this is clarified under Network Policies—

> Libera.Chat’s services are provided by Libera Chat

—which I didn’t think to check when I had questions about the project’s identity. I’d recommend making a similar statement on the About page, and perhaps the Welcome post if it’s not too late for minor revisions.
