### ISSUE TITLE
Setuped nick + nick-backup; now I've got banned for that?

### ISSUE THREAD

**Issue by gree303** [Libera-Chat/libera-chat.github.io#326]
I've been setting up my old irc nick the past hour. Getting into the details to get it right.
For the registration process I've used my local ISP. 
After that I switched back to my VPN - is that the problem here?

Maybe someone knows what is going on, thanks.

**Comment by swantzter** [comment]
Hi, this is the issue tracker for the libera.chat website. If you've been banned there will be an email in the ban message to contact with any questions related to the ban, that way you'll be able to get accurate help.
