### ISSUE TITLE
Evaluate to join "Free Cultural Work" (→ avoid "NC" - not compatible with Wikipedia)

### ISSUE THREAD

**Issue by valerio-bozzolan** [Libera-Chat/libera-chat.github.io#342]
Hi all :)

Thanks for your work here! Long life to IRC.

I very like contributing on Wikimedia Projects also about topics like IRC etc. As you may already know, on Wikimedia Projects everybody there should contribute using "Libre" contents. So just to clarify for newcomers: a Libre content is something available without any practical restriction. For example, a content shared "not for schools" or "not for commercial purposes" is proprietary since it does not allow to create something new and creative that could be used in shools or in radio stations and televisions, (or Wikimedia Projects indeed) etc.

Here some extra details about what is Libre and what is not, in the field of contents:

https://creativecommons.org/public-domain/freeworks/

## Proposal

We can evaluate the drop of the "NC" restriction and adopt just a "SA" copyleft Libre license:

|  |  | Type | Compatible with Wikipedia |
|--|--|--|--|
| Current | [CC BY-NC-SA 4.0](https://github.com/Libera-Chat/libera-chat.github.io/blob/main/LICENSE-content.txt) |  :yellow_circle: Proprietary |  :red_circle: No |
| **Proposed** |  [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) |  :white_check_mark: Libre  | :white_check_mark: Yes |

## FAQ

Question: But I am a non-profit. So I'm non-commercial (?)

Answer: The correlation is wrong. An "NC" license should be adopted by answering the question: do I want to create a commercial monopoly? For example, if you are a millionaire pop singer, do you want to create a commercial monopoly? Pop singers usually answer YES because they want to make truckloads of money, and prohibit others from singing that song on the radio. I don't think we want the "NC" or similar copyright restrictions. Also think about Wikipedia that is a non-profit but available for any purpose.

----

Question: OK but removing the "non commercial" restriction, what if a billionaire company uses my content to make money?

Answer: First of all, the "NC" (non commercial) restriction is not that powerful since it basically disables a lot of positive uses. It's not in fact possible to make any distinction between an evil company and a good company, and we should not try to do this distinction using a copyright license. Think about Wikipedia. Wikipedia encourages you to print Wikipedia and sell Wikipedia on the street or online. This is good since other professional people would spread Wikipedia without thinking about "Uhm, is selling 1$ of CD-ROM a 'commercial' activity?" - "Uhm, is having a banner on my blog a 'commercial' activity and so I should not copy from Wikipedia?" etc. - in short, Wikipedia allows this, because you can sell Wikipedia ONLY as long as NO restriction is added on your derivative work, so this is a positive loop that makes Wikipedia bigger and bigger, since nobody can fork Wikipedia and make it closed. We probably "just" want this nice powerful "copyleft" protection ("SA" - Share Alike) like Wikipedia, and without any attempt to block legitimate creative usages (without "NC") so to encourage all aspects of the copyleft power, over every possible usage.

---

What if we don't change license?

Well, someone will probably fork us one day, by re-writing the site from scratch and adopting a "CC BY-SA" or whatever other Libre tool (or other Libre choices like "CC BY" and "CC Zero"). Forking things to make them Libre happens all the times on the Internet. And maybe we can avoid that proactively. 

---

OK stop it. OK. How to adopt a Libre license?

This is the most difficult part: since we started from a proprietary license, we cannot start from that, to create something Libre. We can probably ping all previous contributors and ask them to explicitly say that they agree with this Libre license. If we reach a good number, in good faith we can probably make this variation.

So we can add in the README something like "Contributions up to this date are in -old license- and current contributions after this date are in this -new libre license-. Please use git blame and contact the past contributors for any clarification. Thanks for your contributions." etc.

----

Other questions / feedback

Please share a comment :) Especially if you are a lawyer! (I'm not a lawyer). Thanks! :)

---

Known threads on the Fediverse:

- https://mastodon.uno/@boz/111855547834849264
- ...
- ...

**Comment by glguy** [comment]
We discussed this and won't be pursuing a license change at this time.

**Comment by valerio-bozzolan** [comment]
> We discussed this and won't be pursuing a license change at this time.

I understand the problem.

I imagine you will agree, however, that the long term direction (before all of us will die, I mean) is to align this nice website with the direction of the software project itself, which is 100% *libera*. Having this inconsistence (having a Free project on a Non-Free website) is not our friend for communication, and it's not a bonus point to reach funds opportunities from Wikimedia Organizations.

Doing a license migration is still possible. Lot of little to enormous conmunities completed similar license changes.

It's OK if we can't alone, but we can just accept outside help.

Next step: just opening this issue again, I think :)

**Comment by valerio-bozzolan** [comment]
> We discussed this and won't be pursuing a license change at this time.

Sorry for necroposting, but would you be so kind to share "why" Libera-Chat would like to continue to have a commercial monopoly over the website contents forever? Thanks for sharing, so that I can better prepare for similar situations in other communities.... 🥰

**Comment by swantzter** [comment]
@valerio-bozzolan it's more of a logistical issue than anything else. A lot of the content is inherited from the old freenode website which had the same licence. We don't have any means to reach out to each original author to ask them to re-license their contributions, nor do we have the time and resources to clean-room rewrite all our content under a new license. We could, in theory, adopt a new license for new content - but that would only apply cleanly to nentirely new pages and those don't happen _that_ often.

**Comment by swantzter** [comment]
You can also find more details of our reasoning in the public minutes from the meeting where this was discussed https://libera.chat/minutes/2024-02-23-public
