### ISSUE TITLE
Validate passwords during application, and explain limitations.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Libera-Chat/libera-chat.github.io#374]
I've set a 128-character and 64-character passwords using the ASCII gamut ("special symbols" and all). As an example, `9N2WF*uGrithxXLOw24mIjJ5RvD^pwnbspZHKga%%2I#ard^RMTFjpjn7QCgNkkV!IxzKKRq68xO*I*cHG3aS6O8yQn2x7s0gW$E$L!bKWm1wVKZVvw6d*uU9wivotp0`. However, every time I've exited and attempted to reauthenticate at https://web.libera.chat/, I'm informed that it's incorrect.

You need to state:

1.	[ ] which characters, if any, are disallowed, and
1.	[ ] whether a maximum length exists (and, if so, what the maximum length is).

**Comment by funderscore1** [comment]
This looks like a Kiwi IRC bug or something? Such a password normally works just fine.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Libera-Chat/libera-chat.github.io/issues/374#issuecomment-2254674917

@funderscore1, I've solely set it at https://web.libera.chat/, using the instructions at https://github.com/Libera-Chat/libera-chat.github.io/blob/b7e77a7618be35e86728e87ae78f2eaebb428074/content/_guides/sendpass.md. I took a cursory look at https://github.com/kiwiirc/kiwiirc/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+password for any relevant issues upstream, and didn't locate any.

**Comment by funderscore1** [comment]
@RokeJulianLockhart Not 'perhaps', it _just_ works :) A lot of people are using such passwords.

**Comment by funderscore1** [comment]
Maybe ask `#libera` or `#KiwiIRC` on Libera.Chat?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Libera-Chat/libera-chat.github.io/issues/374#issuecomment-2254676065

@funderscore1, do you happen to be? If so, which client did you set it via? It'd be worth using to ensure I'm using one which doesn't erroneously truncate or otherwise corrupt it in transit.

**Comment by funderscore1** [comment]
I believe such questions are better asked on #libera, but that's just my opinion. I think this is getting a bit chatty...

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Libera-Chat/libera-chat.github.io/issues/374#issuecomment-2254678393

@funderscore1, I shan't be able to refer back to it easily if I do. Do you know of a client which definitely supports this, so that I can compare?

**Comment by funderscore1** [comment]
Support what? Logging messages? A lot of them do.

**Comment by glguy** [comment]
This is an issue tracker for the website. For IRC support please use #libera

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Libera-Chat/libera-chat.github.io/issues/374#issuecomment-2254681393

@funderscore1, no - that would be off-topic here. I mean the kind of password that I've aforestated.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Libera-Chat/libera-chat.github.io/issues/374#event-13672389964

@glguy, this issue isn't completed yet. The bug remains.
