### ISSUE TITLE
Provide a way to view the current e-mail address attached to an account.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Libera-Chat/libera-chat.github.io#375]
`GET` instead of `SET` in the e-mail replacement command doesn't do anything.

**Comment by swantzter** [comment]
`/msg NickServ INFO`

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Libera-Chat/libera-chat.github.io/issues/375#issuecomment-2254673538

@swantzter, thanks. Where's that documented?

**Comment by funderscore1** [comment]
@RokeJulianLockhart `/msg NickServ help`

**Comment by swantzter** [comment]
@RokeJulianLockhart yeah the help command @funderscore1 mentioned might be a good start, similar commands exists for all our services like ChanServ and MemoServ.
The help command at least is mentioned briefly here https://libera.chat/guides/account#other-settings and other places.

Worthy of note is the HideMail flag (`/msg NickServ HELP SET`), enabled by default, which prevents others from seeing the email of an account
