### ISSUE TITLE
Clarify categories (primary/secondary) of group contacts

### ISSUE THREAD

**Issue by real-or-random** [Libera-Chat/libera-chat.github.io#38]
https://github.com/Libera-Chat/libera-chat.github.io/blob/95be40b21d2ef8008bacb7b2d83abcc183bf2ec1/chanreg.md#L198-L199

I think this relates to "primary/secondary". I was asking on `#libera` and got the (inofficial) response that there's no real formal distinction between primary and secondary. Anyway, I think it would be helpful to document what primary and secondary contacts are instead of just telling people to reach out.  

Also: Should be document what a valid set of contacts look like: Can there be more than one primary? Is "5 primary, 0 secondary" valid? Is "0 primary, 5 secondary" valid?  etc

**Comment by jesopo** [comment]
I believe there's even been some internal confusion about this, but the clarification I put forward is:

secondary GCs cannot appoint or remove primary GCs, but can appoint secondary GCs.

**Comment by real-or-random** [comment]
> I believe there's even been some internal confusion about this, but the clarification I put forward is:
> 
> secondary GCs cannot appoint or remove primary GCs, but can appoint secondary GCs.

I believe this should imply a rule that there must be at least one primary GC. Is this true?

I can open a PR to the chanreg page if you want.

**Comment by swantzter** [comment]
@real-or-random that's why "your NickServ account name" is a separate question form additional group contacts, unless otherwise specified the requestor will be a primary GC

**Comment by real-or-random** [comment]
I see.

**Comment by edk0** [comment]
i wonder if the secondary GC thing is something we should advertise at all. it seems to serve mainly to confuse people. it may make some sense for huge projects with complex requirements, but in general authority to manage one's project registration is derived from demonstrable control of the project itself--a GC hierarchy shouldn't be necessary.

**Comment by swantzter** [comment]
I think it makes sense to mention that it is an option so that those larger projects are aware, but the default should be private, primary if not specified, and we could move the question out of the form and have it in the additional text below. I think that was the original purpose, but it was too vauge and therefor caused more questions than it answered

**Comment by real-or-random** [comment]
> I think it makes sense to mention that it is an option so that those larger projects are aware, but the default should be private, primary if not specified, and we could move the question out of the form and have it in the additional text below. I think that was the original purpose, but it was too vauge and therefor caused more questions than it answered

From my user perspective, I agree. It's probably a useful option to mention, and I don't think it causes confusion per se. What causes confusion is simply that there's no explanation in the form.

**Comment by AbstractBeliefs** [comment]
Should be closed by #107 . We've removed secondary GCs from the public docs for the time being, PAC intend to engage projects on an as-needed basis about them. Secondary contacts still have a place, but they don't need to be a thing most people worry about.

Reopen if you're wanting more changes.
