### ISSUE TITLE
Connecting to IRCCloud bouncer with other clients

### ISSUE THREAD

**Issue by jwheare** [Libera-Chat/libera-chat.github.io#381]
https://github.com/Libera-Chat/libera-chat.github.io/blob/c847b4b88129551460367156b3ca8efb53470bfe/content/_guides/clients.md?plain=1#L156-L163

I appreciate the mention of IRCCloud on the website, and I'm not asking for any further promotion, but I'd just like to note that the comment about the bouncer only working with our own clients is not accurate. Paid users are able to connect with other clients.
https://blog.irccloud.com/bouncer/

**Comment by TheDaemoness** [comment]
@jwheare

> Paid users are able to connect with other clients.
I've PR'd a change to the IRCCloud section to note this. If you have a moment, I would appreciate if you could review the PR for accuracy.

I'd be interested in knowing if there are any clients not developed or maintained by IRCCloud Ltd that use IRCCloud's API.

**Comment by jwheare** [comment]
I've left a review, thanks. I'm not aware of any full 3rd party clients that use the API.
