### ISSUE TITLE
Explain cloaks

### ISSUE THREAD

**Issue by Tilka** [Libera-Chat/libera-chat.github.io#52]
The nick registration guide mentions cloaks without explaining what they are or how to get one.

(To get a cloak, join `#libera-cloak` and say `!cloakme`. A bot will give your account a generic user cloak and then kick you from the channel.)

**Comment by jaybeers** [comment]
Thanks for mentioning this; I just came from the docs and this GitHub issue is the way I learned how to get a cloak.  :slightly_smiling_face:

For what it's worth (although perhaps it's worth slightly more with the big influx of Freenode expats), there's still a bit of a race condition between when you `NICK` to your desired nickname and when the bot sets up your cloak where your real IP can show up in other people's "notify" setups...but that's a technical matter, not a Web site matter.

**Comment by emersonveenstra** [comment]
fixed in #74

**Comment by RealKindOne** [comment]
You can join ```#libera``` and ask for a cloak.
