### ISSUE TITLE
Automatic login support request

### ISSUE THREAD

**Issue by FrostKnight** [Libera-Chat/libera-chat.github.io#56]
I request this, because someone I know is still using freenode, but  would consider leaving, but this is a feature he says that libera chat doesn't have. 

And he says he doesn't have time to constantly login manually...

If you want to say that I am the one requesting it, fine, but yeah...

I wondered if you could add this option.

**Comment by Minoru** [comment]
Hi, a fellow Libera user here. I'm not sure what's meant by "automatic login"; SASL perhaps? Libera has instructions [for SASL](https://libera.chat/guides/sasl) and also [for CertFP](https://libera.chat/guides/certfp). Hope this helps.

**Comment by FrostKnight** [comment]
I'll check this out, thanks, I'll close for now in case this is what he wants... :)

Appreciated!
