### ISSUE TITLE
Re-create catalyst page

### ISSUE THREAD

**Issue by koobs** [Libera-Chat/libera-chat.github.io#58]
The catalyst page provided substantial value and guidelines for productive and respectful discourse and communication on IRC. We (GC's) linked to it all the time, on URL's and in conversations. We'd like to continue to link to it

**Comment by emersonveenstra** [comment]
Just as an update, we have started writing this internally and it should be merged here Soon™

**Comment by emersonveenstra** [comment]
#135 addresses this

**Comment by koobs** [comment]
Thank you!
