### ISSUE TITLE
Stop blocking Tor connections

### ISSUE THREAD

**Issue by TNTBOMBOM** [Libera-Chat/libera-chat.github.io#63]
I would understand (sorta) that it will take time to implement .onion to libera.chat (#5) but i dont understand how it is considered good justification to block Tor users and only accept clearnet IPs? 

I thought libera.chat to be different and more libre than freenode yet there is no different on this point (at least freenode was having onion connection + TLS)...

OFTC doesnt has .onion but it accept onion connection.

I hope to see this fixed.

ThX!

**Comment by swantzter** [comment]
Hi, we've supported Tor connections through an .onion for a few days now, you can read up on how to connect using it on https://libera.chat/guides/connect#accessing-liberachat-via-tor

Hope that helps

**Comment by TNTBOMBOM** [comment]
Yeah but need TLS... Its the exact same thing copy/paste from freenode 
nothing new.

I wish to see libera.chat to be like OFTC or hackint to allow normal 
pure Tor connection out of the box without headaches.

ThX!

Svante Bengtson:
> Hi, we've supported Tor connections through an .onion for a few days now, you can read up on how to connect using it on https://libera.chat/guides/connect#accessing-liberachat-via-tor
> 
> Hope that helps
>
