### ISSUE TITLE
Add the eir/Sigyn equivalent to the FAQ

### ISSUE THREAD

**Issue by NetSysFire** [Libera-Chat/libera-chat.github.io#65]
There has been a lot of confusion about the availability of Sigyn, eir and similar. There is [ozone](https://github.com/Libera-Chat/Sigyn) which provides Sigyn-like functionality and litharge which is similar to eir.

It should be documented in the FAQ or a similar document that the network uses those. It may also be a good idea to mention the most important differences between ozone/litharge/etc and the freenode-equivalents since many are used to them.

**Comment by examknow** [comment]
I think a knowledge base page listing all the public utility bots, their purpose, and how to use them (if applicable) would be useful.
