### ISSUE TITLE
Add the meaning of "Libera Chat" to the about page/FAQ

### ISSUE THREAD

**Issue by NetSysFire** [Libera-Chat/libera-chat.github.io#68]
Briefly discussed in `#libera`, since quite a few people have been asking about why the name "Libera Chat" was chosen, it may be a good idea to add that to the about page or the FAQ or similar. Some have also been asking about the "deeper meaning" of the name.

**Comment by AbstractBeliefs** [comment]
We wanted a name that alluded to foss-aligned freedoms, think liberty, liberate, etc. We were under a bit of time pressure so there wasn't exactly a serious effort put into libera lore. I think it would be a mistake to try and find a deeper/hidden meaning. I don't really think there's enough motive behind it to justify an in-depth explanation on the website.
