### ISSUE TITLE
[Documentation] Available channels, ideally as a queryable API

### ISSUE THREAD

**Issue by rubyFeedback** [Libera-Chat/libera-chat.github.io#80]
I heard how freenode died. I was using it years ago, have not used it in a long while.

Now libera is probably taking a while but I am considering resuming on #ruby and
a few channels eventually. I haven't yet managed to make a decision in this
regard, because my primary use case of retirement was lack of time, and this
is still a given. Anyway - would it be possible to sort of show statistics or something
like that? At the least which channels are available, but ideally also how active
these are (does not have to be daily numbers, it's perfectly fine to bin it and
present it as e. g. 0-10, 11-20 or so; this is really just meant as a general 
overview query, not a detailed thing. I kind of want to know how active libera
may be before I decide whether to invest time into oldschool IRC again).
Thanks for reading at the least!

**Comment by swantzter** [comment]
You coild perhaps use alis, or netsplit.de as listed on https://libera.chat/guides/findingchannels
Those are the "state of the art" tools I'd say

**Comment by swantzter** [comment]
I'm going to close this since it's not directly related to the website but rather and extension of the ircd or services
