### ISSUE TITLE
Banned From NickServ

### ISSUE THREAD

**Issue by moriel5** [Libera-Chat/libera-chat.github.io#84]
Hello, I am currently trying to join the Solus channels on Libera (moving from FreeNode), and thus I am trying to register a nickname, however I am getting banned from NickServ for some odd reason, despite the fact that I have never even connected to the Libera network before.

Clients used for this: Polari and the official Libera web client (thinking that there may be a bug in Polari).

**Comment by swantzter** [comment]
This is the issue tracker for our website, not for network support. Please contact staff via irc if you can connect (join `#libera`, or get a list of available staff with `/stats p`) or email support@libera.chat. You'll need to include more detail than you've done here, like the error message NickServ gives you

**Comment by moriel5** [comment]
Yeah, sorry about that.
I could understand who to turn to, that is why I opened an issue here.

In any case, the bans keep on going on and off, but I managed to register my nickname in the end, so that's taken care of.
