### ISSUE TITLE
Add a troubleshooting guide with common errors/issues and how to solve them.

### ISSUE THREAD

**Issue by AbstractBeliefs** [Libera-Chat/libera-chat.github.io#86]
It would be good to have a single page where people could read, or ctrl+f for keywords from error messages, to get a quick overview of what went wrong, and signposted on to how to fix it.

Examples:
- [ ] "You need to identify via SASL to use this server" (SASLified range bans)
- [ ] "Cannot send to nick/channel" (+q on channel, often non-specific like +q $~a)
- [ ] "Cannot change nickname while banned on channel" (esp when it's actually quieted)
- [ ] "You must log in with services to message this user" (target is +R)

More to add, I'm sure.

**Comment by Sanyam17-beep** [comment]
hey i wanted to work on it please assign this to me
@AbstractBeliefs

**Comment by Sanyam17-beep** [comment]
and please tell to add it in main readme or create a new readme

**Comment by AbstractBeliefs** [comment]
Hi @Sanyam17-beep , thanks for having a look. I would suggest you create a new troubleshooting.md file under content_/guides - there are similar files in there you might want to read for examples on formatting.

I'm not assigning this ticket to anyone as I expect it will grow and we complete bullet points in PRs as we go.

**Comment by Sanyam17-beep** [comment]
thank you for your help @AbstractBeliefs

**Comment by emersonveenstra** [comment]
fixed in #125

**Comment by TheGiraffe3** [comment]
Should the `help wanted` label be removed from this?
