### ISSUE TITLE
Request to allow double bridging

### ISSUE THREAD

**Issue by ftyers** [Libera-Chat/libera-chat.github.io#91]
There are a few channels/communities that have become fragmented with all the stuff going on and are now split between IRC, Matrix, Discord, Telegram, etc. It is possible to bridge all of these with Matrix into a single channel, but afaik Libera does not allow double bridging on the Matrix side (e.g. we can't bridge to both Discord and Libera at the same time). 

Would it be possible to allow double bridging so that these communities can once again share a channel/communication space. Thanks for the consideration.

**Comment by swantzter** [comment]
I'm going to mark this with "invalid" since it has nothing to do with our website, I'll leave it open for now to allow discussion/let someone more versed in how matrix works from our side weigh in

**Comment by ftyers** [comment]
I'm happy to move the issue somewhere else if there is a more appropriate place for it :)

**Comment by emersonveenstra** [comment]
We just published an FAQ about matrix (https://libera.chat/guides/faq#can-i-connect-with-matrix) (also see #113). Double-bridging is mostly okay, if there's several hundred or thousands of bridged users with very few using IRC, we might ask that you use heisenbridge instead.
