### ISSUE TITLE
Add a page which lists the Libera Chat staff

### ISSUE THREAD

**Issue by SadieCat** [Libera-Chat/libera-chat.github.io#93]
One of the criticisms of *the previous network* was that the staff were seen as a fairly opaque group which most people didn't really know or have interactions with and several staff members I've spoken to have said that they wish they had done more to make it not like this.

One way to solve this would be to have a staff page on the website where people can find out about the staff team and get to know them a bit better. It could also have links to GitHub Sponsors or some similar services for where people can throw money at the volunteers who have helped them.

Some examples of this from other networks:

- https://www.oftc.net/staff/
- https://snoonet.org/staff/
- http://www.geekshed.net/staff/

**Comment by ncoevoet** [comment]
This list: https://libera.chat/about#wider-staff-and-organisation-membership

**Comment by SadieCat** [comment]
A list of nicknames buried in an about page feels a bit opaque to me and it could probably be expanded upon.

**Comment by swantzter** [comment]
I'm not sure i agree that it's "buried" - it's the overwhelming majority of the content of the about page, (staff members and their roles) and it describes what each (group of) people does. And /about feels like a pretty logical place to answer the question "who we are and what we do"
